### ISSUE TITLE
Misalignment of text 

### ISSUE THREAD

**Issue by fomap** [UNICEFECAR/USupport-entry-bundle#127]
From now on any misalignment with their placement and screenshots will be fixated in following table:
https://docs.google.com/spreadsheets/d/1zMjNlUAuD47osRgS8jUS4npFhgPI2L2z1lwHeqyEg2I/edit?usp=sharing

**Desktop **

OS: Windows 10
Browser chrome
Version latest
**Smartphone **

Device: Xiaomi redmi 10s
OS: Android 13
Browser chrome
Version latest

**Comment by sebastian-7DIGIT** [comment]
@fomap  I would personally suggest using GitHub for each adjustment that needs to be made; otherwise, we will end up in the same scenario we found ourselves in a couple of months ago.

We suggest using the GitHub board for issue tracking. You can either create separate issues for each adjustment or set of similar adjustments, which is the preferred way, or create a general issue such as this one and add comments to it containing further adjustments. The second approach might work but it can sometimes bring confusion.

Open to having a call to present the proposed workflow once more.
