### ISSUE TITLE
Consultant answered the question in Q/a but the published answer was not what was typed

### ISSUE THREAD

**Issue by Gaskevych** [UNICEFECAR/USupport-entry-bundle#19]
**Describe the bug**
One consultant during the testing session noticed that he answered a question and the answer which was published provided completely different information (not what he typed). Question was – How to cope with anxiety. Answer was about feeling of sound (photo attached). 

**To Reproduce**

Go to Q/A as a provider and try answering a question in Russian. 

**Screenshots**
![Picture2](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/146723847/ed78612d-4043-4fa5-be22-f49343f6f976)

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych We followed the provided steps for replication but were unable to identify the reported issue. Additionally, we tested the behavior of the My QA module, including different languages, and encountered no problems on our end. 

Kindly share more details so that we can conduct a more in-depth investigation, otherwise, I may recommend closing this issue.
