### ISSUE TITLE
Slider in Registration/Log in (client, web) moves too fast

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#39]
**Is your feature request related to a problem?**
Participants who used the web version of the platform noted that the slider moved too quickly and it was difficult to read the information.

**Describe the solution you'd like**
Make the slider slower so the users have time to read through the information.

**Additional comments**
The slider is too fast and scrolls even if you try to hold it with the mouse. I also don’t like the fact that not the entire page is displayed (although it would fit perfectly within one screen) and you have to scroll through it.

![Screenshot 2023-10-11 at 9 41 35](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/126719842/7764b781-e79c-48dd-b83f-b13c15eb6601)

**Comment by sebastian-7DIGIT** [comment]
@Gaskevych We will need further clarification for the following part of the issue "I also don’t like the fact that not the entire page is displayed (although it would fit perfectly within one screen) and you have to scroll through it." 

Is the problem the fact that Clients need to scroll the page to see all the options available (see Picture 1 below)? 

If this is the issue we can reduce the space highlighted with red bellow.

Please confirm if this is the desired change, otherwise please provide more details.

### Initial Load
<img width="1791" alt="Screenshot 2023-10-13 at 10 25 40" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/109344321/d03efba7-9bab-49ed-b915-cc7869b2906d">


### Scrolled view
<img width="1792" alt="Screenshot 2023-10-13 at 10 24 53" src="https://github.com/UNICEFECAR/USupport-entry-bundle/assets/109344321/6ad207fa-e20e-4e8f-8f10-ef8e97c09ac1">

**Comment by sebastian-7DIGIT** [comment]
The slider speed was decreased. 

@Gaskevych could you please provide clarification for the comment above?

**Comment by Gaskevych** [comment]
@sebastian-7DIGIT yes, please remove the space in a red square. Thanks!

**Comment by sebastian-7DIGIT** [comment]
Changes were implemented, and ready for deployment. @vasilen-7DIGIT
