### ISSUE TITLE
Reset password email link arriving late or not arriving at all

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#42]
**Describe the bug**
An email with a link to reset a password arrives with a long delay (if it arrives at all). Also, when changing the password, you can only log in to the website again; the password in the application is not updated, which is why you cannot log in.

**To Reproduce**
1. Go to [https://staging.usupport.online/client/login](https://staging.usupport.online/client/login)
2. Click on "I forgot my password"
3. Enter email address
4. Wait for the reser password email

**Expected behavior**
The forgot password email to come in short time frame, and the passwrod to be updated in whe whole website.

**Desktop:**
 - OS: [Mac]
 - Browser [Chrome, Safari, Firefox, Opera, Yandex]
 - Version [latest]

**Smartphone:**
 - Device: [iphone, android]
 - OS: [latest]
 - Browser [Safari, Chrome]
 - Version [latest]

**Additional context**
Could not reproduce the described problem. After several attempts the reset password email came within short time frame from the submition and after successfully reseting the password the functionality was working as expected. Additinal information is needed.

**Comment by fomap** [comment]
Password reset was tested, everything works fine. 
Logged in both browser (chrome latest version) and application

**Comment by MiriamObibi** [comment]
Using chrome, it took 5mins to arrive, this may be considered as a delay. 
It is important to mention that the issue was originally reported to have been observed in a setting where at least 20 clients + 20 providers were testing the platform at the same time. Presumably, load conditions on the platform may have contributed to the email delivery delays/failures, which would necessitate further investigations. Please kindly investigate.
