### ISSUE TITLE
“American support provider” appears on the address tab of all providers throughout the work on the platform

### ISSUE THREAD

**Issue by cshishkov-7DIGIT** [UNICEFECAR/USupport-entry-bundle#51]
**Describe the bug**
It turns out that “American support provider” appears on the address tab of all providers throughout the work on the platform.

**Expected behavior**
Additional information is neded.

**Desktop:**
 - OS: [Mac]
 - Browser [Chrome, Safari, Firefox, Opera, Yandex]
 - Version [latest]

**Smartphone:**
 - Device: [iphone, android]
 - OS: [latest ios, latest android]
 - Browser [Safari, Chrome]
 - Version [latest]

**Additional context**
Additional information is needed to reproduce this bug.

**Comment by Gaskevych** [comment]
Anel, can you please test it when you will be checking from the providers' account? it should be in Russian or Kazakh Thanks!

**Comment by Gaskevych** [comment]
@fomap please check this one

**Comment by Gaskevych** [comment]
couldn't get more details on this issue

**Comment by gravitz** [comment]
@Gaskevych. My reading of this from the reports was that the website title (title tag visible on the tab/window title) that currently reads USupport provider may have been misread as **US** support provider by users (US the country). Rewording this to Usupport instead of USupport (which we should do everywhere anyway since that is the correct spelling) could be the easy fix. Otherwise we have a branding problem.

![image](https://github.com/UNICEFECAR/USupport-entry-bundle/assets/10649892/989ad9d3-80d8-443b-aede-638996f4bf7b)

**Comment by MiriamObibi** [comment]
@sebastian-7DIGIT @Gaskevych as agreed, let's update the title of the page to uSupport to avoid this confusion.

**Comment by sebastian-7DIGIT** [comment]
@MiriamObibi the changes which you requested are in development under issue #76
