### ISSUE TITLE
Premature session timeouts - Kazakh feedback

### ISSUE THREAD

**Issue by MiriamObibi** [UNICEFECAR/USupport-entry-bundle#58]
**Describe the bug**

Provider interface: If a page is accidentally closed or there is a need to go to another page, and/or refresh, login process is to be done on the same device again 

**To Reproduce**
Login (tested as a provider on web but clients have also reported a similar issue) 
Go to any other page on the web app after login in (e.g. Activity history) 
Leave the tab/window, to go to another website 
Return to the open usupport browser tab/window (before the inactivity timeout expires) 
Click on another usupport page (continue browsing as usual) or refresh the page you left open. 
 

**Expected behavior**
Users should not be required to log in again unless the inactivity time out has expired.

**Screenshots**
None. 

**Desktop (please complete the following information):**
 - OS:  MacOS, Windows
 - Browser: Chrome,Safari

**Smartphone (please complete the following information):**
 No

**Additional context**

**Comment by sebastian-7DIGIT** [comment]
@MiriamObibi 

Regrettably, we are unable to address situations where a user accidentally closes the browser tab. Our recommendation is to encourage users to exercise caution when performing this action, especially if the login process causes inconvenience.

From a technical standpoint, the requirement is quite clear: when a browser tab is closed, the user session should be terminated, necessitating the user to log in again. This is the expected behaviour across all platforms at this moment in time. According to requirements raised from previous conversations with Vikas.

It’s worth noting that in some specific scenarios and browsers, this implementation faces a minor issue that cannot be resolved without deviating from the requirement of destroying the user session when the tab is closed.

One such scenario arises when a user is logged in on either a single or two separate tabs within the same browser. In certain situations, refreshing the page may prompt the user to log in again.

One potential solution to this problem is to restrict the user session to a single tab. This means that when a user attempts to access any interface in separate tabs, they will need to log in every time.

Could you please confirm whether this proposed solution meets your requirements?

**Comment by MiriamObibi** [comment]
@sebastian-7DIGIT i understand this can be the case when the browser tab is mistakenly closed. Did you also test to see what happens when they leave the usupport tab to a different tab and come back? It logs the user off and they need to register again everytime. A provider may be on a chat/call with a patient and want to quickly google something and get back only to be asked to register again. Could you help check this? I know there is an inactivity period that has been set a while back, after which the user is logged off from the system. Let's make sure this is still the case.

**Comment by sebastian-7DIGIT** [comment]
@MiriamObibi upon reevaluation, we've observed the platform's behaviour when a user switches tabs and returns. The previously reported issue is no longer present, and we've deactivated session timeout during consultations. This ensures that providers or clients won't need to sign in again if they're not actively using the platform during a consultation. 

Please have a look and let me know if we can close this issue. 
Thanks!
