### ISSUE TITLE
Failed login redirect- Kazakh feedback

### ISSUE THREAD

**Issue by MiriamObibi** [UNICEFECAR/USupport-entry-bundle#61]
**Describe the bug**
Provide interface: On signing in, report(s) (by a provider) of failure to complete the login. It failed to redirect to the platform's landing page until the page is manually reloaded. 

**To Reproduce**
Unable to reproduce

**Expected behavior**
Redirection to the landing (secure) pages of the provider's interface

**Comment by sebastian-7DIGIT** [comment]
We could not replicate the issue after several attempts on different browsers and operating systems.

@MiriamObibi We will need more specific details on how to replicate the issue.

**Comment by MiriamObibi** [comment]
@sebastian-7DIGIT  we could not replicate this but wanted to ensure it is checked as much as possible on different browsers. Since it was highlighted as an issue during the Kazakh test, It needs to be tested vigorously by your team. Thanks

**Comment by sebastian-7DIGIT** [comment]
We have already tested this multiple times before transferring the issue to GitHub. With the information we had, we were unable to replicate the problem. Furthermore, the testing we conducted encompassed various scenarios that we devised internally (including different browsers).

If you have any additional details that we can investigate, please share them with us, and we'll conduct further testing.

Otherwise, I suggest temporarily closing this issue. Thank you.

**Comment by MiriamObibi** [comment]
Since this has been extensively tested, please proceed as recommended to close it temporarily
